[pytest]
DJANGO_SETTINGS_MODULE = fileconverter.settings
python_files = tests.py test_*.py *_tests.py
addopts = -q

[coverage:run]
branch = true
omit =
    */migrations/*
    */tests/*
    manage.py

[coverage:report]
exclude_lines =
    pragma: no cover
    raise NotImplementedError
    if TYPE_CHECKING:
