# "Database migration 0002: usagequota uniq usagequota org workspace."
# Generated by Django 5.2.15 on 2026-07-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("quotas", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="usagequota",
            constraint=models.UniqueConstraint(
                fields=("organization", "workspace"),
                name="uniq_usagequota_org_workspace",
            ),
        ),
    ]
