# "Database migration 0001: initial."
# Generated by Django 5.2.14 on 2026-07-02 22:43

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("files", "0001_initial"),
        ("organizations", "0001_initial"),
        ("quotas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversionBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("target_format", models.CharField(blank=True, max_length=24)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("done", "Done"),
                            ("partial", "Partial success"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("total_jobs", models.PositiveIntegerField(default=0)),
                ("completed_jobs", models.PositiveIntegerField(default=0)),
                ("failed_jobs", models.PositiveIntegerField(default=0)),
                ("cancelled_jobs", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "batch_zip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batch_zips",
                        to="files.fileblob",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.workspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConversionJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("source_format", models.CharField(max_length=24)),
                ("target_format", models.CharField(max_length=24)),
                ("detected_mime", models.CharField(blank=True, max_length=160)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("scanning", "Scanning"),
                            ("scan_failed", "Scan failed"),
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("retrying", "Retrying"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                (
                    "progress_mode",
                    models.CharField(default="indeterminate", max_length=24),
                ),
                (
                    "progress_percent",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("progress_message", models.CharField(blank=True, max_length=160)),
                ("converter_name", models.CharField(max_length=80)),
                ("converter_version", models.CharField(max_length=40)),
                ("option_payload", models.JSONField(blank=True, default=dict)),
                ("option_schema_version", models.CharField(default="1", max_length=40)),
                ("celery_task_id", models.CharField(blank=True, max_length=255)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("retry_classification", models.CharField(blank=True, max_length=60)),
                ("failure_reason", models.CharField(blank=True, max_length=240)),
                ("internal_error_code", models.CharField(blank=True, max_length=80)),
                ("internal_error_detail", models.TextField(blank=True)),
                ("original_display_filename", models.CharField(max_length=255)),
                ("input_byte_size", models.PositiveBigIntegerField(default=0)),
                ("output_byte_size", models.PositiveBigIntegerField(default=0)),
                ("input_checksum", models.CharField(blank=True, max_length=64)),
                ("output_checksum", models.CharField(blank=True, max_length=64)),
                (
                    "malware_scan_verdict",
                    models.CharField(default="not_configured", max_length=40),
                ),
                ("idempotency_key", models.CharField(max_length=160)),
                ("worker_id", models.CharField(blank=True, max_length=120)),
                ("claim_generation", models.PositiveIntegerField(default=0)),
                ("cancel_requested", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("queued_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="conversions.conversionbatch",
                    ),
                ),
                (
                    "input_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="input_jobs",
                        to="files.fileblob",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
                (
                    "output_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="output_jobs",
                        to="files.fileblob",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quota_decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="quotas.quotadecision",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("event_type", models.CharField(max_length=80)),
                ("message", models.CharField(blank=True, max_length=260)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="conversions.conversionjob",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="conversionjob",
            index=models.Index(
                fields=["workspace", "-created_at"],
                name="conversions_workspa_55f499_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversionjob",
            index=models.Index(
                fields=["owner", "-created_at"], name="conversions_owner_i_cde83b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversionjob",
            index=models.Index(
                fields=["status", "updated_at"], name="conversions_status_909a04_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversionjob",
            index=models.Index(
                fields=["expires_at"], name="conversions_expires_8bdc65_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="conversionjob",
            constraint=models.UniqueConstraint(
                fields=("owner", "workspace", "idempotency_key"),
                name="uniq_job_idempotency_per_actor_workspace",
            ),
        ),
    ]
