# "Database migration 0002: outboxevent attempts outboxevent last attempt at and more."
# Generated by Django 5.2.15 on 2026-07-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="outboxevent",
            name="attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="outboxevent",
            name="last_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="outboxevent",
            name="last_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name="outboxevent",
            index=models.Index(
                fields=["delivered_at", "created_at"],
                name="audit_outbo_deliver_363602_idx",
            ),
        ),
    ]
