# "Database migration 0001: initial."
# Generated by Django 5.2.14 on 2026-07-02 22:43

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.files.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileBlob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("input", "Input"),
                            ("output", "Output"),
                            ("temp", "Temporary"),
                            ("batch_zip", "Batch ZIP"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=600, upload_to=apps.files.models.blob_upload_to
                    ),
                ),
                ("original_name", models.CharField(blank=True, max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=160)),
                ("byte_size", models.PositiveBigIntegerField(default=0)),
                ("sha256", models.CharField(blank=True, db_index=True, max_length=64)),
                ("encryption", models.CharField(default="local-dev", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.workspace",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "workspace", "sha256"],
                        name="files_fileb_organiz_dba3bf_idx",
                    ),
                    models.Index(
                        fields=["kind", "created_at"],
                        name="files_fileb_kind_4acba5_idx",
                    ),
                ],
            },
        ),
    ]
